import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'
import astGrepPlugin from 'eslint-plugin-ast-grep'

export default defineConfig([
  // `.claude` holds nested git worktrees (agent workspaces) — full repo
  // checkouts that must never be linted as part of this tree's `eslint .`.
  // src/types/database.types.ts is generated by `npm run gen:types` (Supabase
  // CLI output); its style is not ours to lint.
  // `**/.venv` keeps `eslint .` out of any Python virtualenv a dev creates by
  // running a package's pytest locally (uv git-ignores it, but eslint still
  // walks it).
  globalIgnores(['dist', '.vite', 'node_modules', '.claude', '**/.venv', 'src/types/database.types.ts']),
  // TypeScript files (the migration is incremental — most of the tree is still
  // .js/.jsx; see tsconfig.json). Type-aware linting at the `strictTypeChecked`
  // tier + `projectService` pull in the type-checker so rules like
  // no-floating-promises / no-misused-promises / no-unsafe-* / no-unnecessary-*
  // can catch bugs `tsc --noEmit` won't (unawaited promises, `any` leaking in
  // from untyped JSON, redundant casts). Scoped to the .ts/.tsx files the
  // migration has reached, so it stays cheap until coverage grows.
  {
    // Scoped to src/ (the SPA migration target); the Deno edge functions under
    // supabase/functions have their own runtime + console conventions.
    files: ['src/**/*.{ts,tsx}'],
    extends: [
      tseslint.configs.strictTypeChecked,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
      parserOptions: {
        ecmaVersion: 'latest',
        ecmaFeatures: { jsx: true },
        sourceType: 'module',
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-var': 'error',
      'prefer-const': 'error',
      'no-throw-literal': 'error',
      'no-unneeded-ternary': 'error',
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      // verbatimModuleSyntax is on (tsconfig); enforce `import type` to match.
      '@typescript-eslint/consistent-type-imports': 'error',
      // These two strictTypeChecked rules assume the type-checker's view is
      // ground truth. It isn't at this app's boundaries: the read model is loose
      // JSON (Supabase rows / NDJSON) whose declared types are aspirational, so
      // `Number(data.x)` coercions (PostgREST returns numerics as strings) and
      // `if (data)` / `?? []` guards are deliberate runtime defenses the rules
      // would have us delete. Off — keep the guards; the no-unsafe-* family
      // still polices genuine `any` leaks.
      '@typescript-eslint/no-unnecessary-condition': 'off',
      '@typescript-eslint/no-unnecessary-type-conversion': 'off',
      // Numbers in template literals are idiomatic (e.g. `${count} lots`).
      '@typescript-eslint/restrict-template-expressions': ['error', { allowNumber: true }],
      // set-state-in-effect requires React Compiler to produce meaningful
      // diagnostics; without it the rule fires on valid patterns (syncing
      // external values to local state, early-return guards, one-way latches).
      // Disable until the project adopts React Compiler.
      'react-hooks/set-state-in-effect': 'off',
    },
  },
  {
    // node:test's `test(...)` returns a Promise the runner itself awaits, so a
    // top-level `test(...)` call is a floating promise by design — the rule is
    // a false positive for the whole test-runner idiom. Tests also use `!` on
    // known-good fixtures, where a non-null assertion is clearer than a guard.
    files: ['src/**/*.test.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-floating-promises': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },
  {
    files: ['**/*.{js,jsx}'],
    extends: [
      js.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
      parserOptions: {
        ecmaVersion: 'latest',
        ecmaFeatures: { jsx: true },
        sourceType: 'module',
      },
    },
    rules: {
      'no-unused-vars': ['error', { varsIgnorePattern: '^[A-Z_]' }],
      // Correctness
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-var': 'error',
      'prefer-const': 'error',
      'no-throw-literal': 'error',
      'no-unneeded-ternary': 'error',
      'no-implicit-coercion': ['error', { allow: ['!!'] }],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      // Encourage typedef hints / discourage silent `any`-style holes
      'valid-typeof': 'error',
      // See TS block above for rationale.
      'react-hooks/set-state-in-effect': 'off',
    },
  },
  // Node.js scripts and test infrastructure — need process/console/etc.
  {
    files: ['playwright.config.js', 'playwright.*.config.js', 'tests/**/*.js', 'scripts/**/*.js'],
    languageOptions: {
      globals: { ...globals.node },
    },
    rules: {
      'no-console': 'off',
    },
  },
  // Structural rules via ast-grep — catch patterns that are legal JS/TS but
  // violate project conventions agents would otherwise naturally write wrong.
  // net.js     — fetchWithRetry implementation (raw fetch intentional)
  // telemetry.js — posthog singleton wrapper (posthog.init/capture intentional)
  // supabase.js  — Supabase singleton (createClient call intentional)
  // useSemanticSearch + useImageSearch — HF Inference API clients (raw fetch intentional)
  {
    files: ['src/**/*.{js,jsx,ts,tsx}'],
    ignores: [
      'src/utils/net.js',
      'src/lib/telemetry.js',
      'src/lib/supabase.js',
      'src/hooks/useSemanticSearch.js',
      'src/hooks/useImageSearch.js',
    ],
    plugins: { 'ast-grep': astGrepPlugin },
    rules: {
      'ast-grep/no-restricted-syntax': ['error',
        {
          pattern: 'fetch($$$)',
          message: 'Use fetchWithRetry / fetchJsonWithRetry / fetchTextWithRetry from src/utils/net.js — they add exponential-backoff retries on 5xx and network errors.',
        },
        {
          pattern: 'posthog.capture($$$)',
          message: 'Use captureEvent() from src/lib/telemetry.js — it checks isAnalyticsConfigured and no-ops when PostHog is unconfigured.',
        },
        {
          pattern: 'posthog.init($$$)',
          message: 'PostHog is initialized once in src/lib/telemetry.js — do not call posthog.init() elsewhere.',
        },
        {
          pattern: 'createClient($$$)',
          message: 'Import the supabase singleton from src/lib/supabase.js — do not instantiate a new Supabase client (a second client bypasses the shared auth session).',
        },
        {
          pattern: 'dangerouslySetInnerHTML={$$$}',
          message: 'dangerouslySetInnerHTML bypasses React\'s XSS protection — this app never needs it; use JSX children instead.',
        },
        {
          pattern: 'useVirtualizer($$$)',
          message: 'Use useWindowVirtualizer() instead — the app scrolls the window, not a container div; useVirtualizer needs an explicit scrollElement and would silently render all items without one.',
        },
      ],
    },
  },
  // QueryClient must be the singleton from src/lib/queryClient.js. Test files
  // legitimately create isolated clients per test, so they're exempt.
  {
    files: ['src/**/*.{js,jsx,ts,tsx}'],
    ignores: [
      'src/lib/queryClient.js',
      'src/**/*.{test,vitest}.{js,jsx,ts,tsx}',
    ],
    plugins: { 'ast-grep': astGrepPlugin },
    rules: {
      'ast-grep/no-restricted-syntax': ['error',
        {
          pattern: 'new QueryClient($$$)',
          message: 'Import the singleton queryClient from src/lib/queryClient.js — a second QueryClient gets its own isolated cache and breaks shared server state.',
        },
      ],
    },
  },
])
