import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // `.claude` holds nested git worktrees (agent workspaces) — full repo
  // checkouts that must never be linted as part of this tree's `eslint .`.
  // src/types/database.types.ts is generated by `npm run gen:types` (Supabase
  // CLI output); its style is not ours to lint.
  // `**/.venv` keeps `eslint .` out of any Python virtualenv a dev creates by
  // running a package's pytest locally (uv git-ignores it, but eslint still
  // walks it).
  globalIgnores(['dist', '.vite', 'node_modules', '.claude', '**/.venv', 'src/types/database.types.ts']),
  // TypeScript files (the migration is incremental — most of the tree is still
  // .js/.jsx; see tsconfig.json). Type-aware linting at the `strictTypeChecked`
  // tier + `projectService` pull in the type-checker so rules like
  // no-floating-promises / no-misused-promises / no-unsafe-* / no-unnecessary-*
  // can catch bugs `tsc --noEmit` won't (unawaited promises, `any` leaking in
  // from untyped JSON, redundant casts). Scoped to the .ts/.tsx files the
  // migration has reached, so it stays cheap until coverage grows.
  {
    // Scoped to src/ (the SPA migration target); the Deno edge functions under
    // supabase/functions have their own runtime + console conventions.
    files: ['src/**/*.{ts,tsx}'],
    extends: [
      tseslint.configs.strictTypeChecked,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
      parserOptions: {
        ecmaVersion: 'latest',
        ecmaFeatures: { jsx: true },
        sourceType: 'module',
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-var': 'error',
      'prefer-const': 'error',
      'no-throw-literal': 'error',
      'no-unneeded-ternary': 'error',
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      // verbatimModuleSyntax is on (tsconfig); enforce `import type` to match.
      '@typescript-eslint/consistent-type-imports': 'error',
      // These two strictTypeChecked rules assume the type-checker's view is
      // ground truth. It isn't at this app's boundaries: the read model is loose
      // JSON (Supabase rows / NDJSON) whose declared types are aspirational, so
      // `Number(data.x)` coercions (PostgREST returns numerics as strings) and
      // `if (data)` / `?? []` guards are deliberate runtime defenses the rules
      // would have us delete. Off — keep the guards; the no-unsafe-* family
      // still polices genuine `any` leaks.
      '@typescript-eslint/no-unnecessary-condition': 'off',
      '@typescript-eslint/no-unnecessary-type-conversion': 'off',
      // Numbers in template literals are idiomatic (e.g. `${count} lots`).
      '@typescript-eslint/restrict-template-expressions': ['error', { allowNumber: true }],
      // set-state-in-effect requires React Compiler to produce meaningful
      // diagnostics; without it the rule fires on valid patterns (syncing
      // external values to local state, early-return guards, one-way latches).
      // Disable until the project adopts React Compiler.
      'react-hooks/set-state-in-effect': 'off',
    },
  },
  {
    // node:test's `test(...)` returns a Promise the runner itself awaits, so a
    // top-level `test(...)` call is a floating promise by design — the rule is
    // a false positive for the whole test-runner idiom. Tests also use `!` on
    // known-good fixtures, where a non-null assertion is clearer than a guard.
    files: ['src/**/*.test.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-floating-promises': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },
  {
    files: ['**/*.{js,jsx}'],
    extends: [
      js.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
      parserOptions: {
        ecmaVersion: 'latest',
        ecmaFeatures: { jsx: true },
        sourceType: 'module',
      },
    },
    rules: {
      'no-unused-vars': ['error', { varsIgnorePattern: '^[A-Z_]' }],
      // Correctness
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-var': 'error',
      'prefer-const': 'error',
      'no-throw-literal': 'error',
      'no-unneeded-ternary': 'error',
      'no-implicit-coercion': ['error', { allow: ['!!'] }],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      // Encourage typedef hints / discourage silent `any`-style holes
      'valid-typeof': 'error',
      // See TS block above for rationale.
      'react-hooks/set-state-in-effect': 'off',
    },
  },
  // Node.js scripts and test infrastructure — need process/console/etc.
  {
    files: ['playwright.config.js', 'playwright.*.config.js', 'tests/**/*.js', 'scripts/**/*.js'],
    languageOptions: {
      globals: { ...globals.node },
    },
    rules: {
      'no-console': 'off',
    },
  },
])
