// Turns raw benchmark results into a scored, human-readable report.
//
// Four headline dimensions map to the site's stated goals:
//   Usable      — did bidders complete their objectives?
//   Intuitive   — did they take roughly the optimal number of steps?
//   Fast        — load + interaction latency against budget
//   Responsive  — layout integrity across phone/tablet/desktop
// Accessibility is scored and reported alongside as a fifth dimension.

import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname } from 'node:path'

const clamp = (n, lo = 0, hi = 100) => Math.max(lo, Math.min(hi, n))

// Map a latency to a 0–100 score against good/ok/poor budgets (ms).
function latencyScore(ms, good, ok, poor) {
  if (ms == null) return null
  if (ms <= good) return 100
  if (ms <= ok) return 80
  if (ms <= poor) return 60
  return 35
}

function grade(score) {
  if (score >= 90) return 'A'
  if (score >= 80) return 'B'
  if (score >= 70) return 'C'
  if (score >= 60) return 'D'
  return 'F'
}

export function buildScorecard(r) {
  const objs = r.objectives
  const scored = objs.filter(o => o.status !== 'blocked')
  const passed = scored.filter(o => o.status === 'pass')

  // Usable: share of (non-blocked) objectives completed.
  const usable = scored.length ? (passed.length / scored.length) * 100 : 0

  // Intuitive: how close to the optimal step count, averaged over completed tasks.
  const efficiencies = passed.map(o => clamp((o.optimalSteps / Math.max(o.steps, 1)) * 100))
  const intuitive = efficiencies.length
    ? efficiencies.reduce((a, b) => a + b, 0) / efficiencies.length
    : 0

  // Fast: blend of data-ready, FCP, and interaction latencies.
  const p = r.perf || {}
  const speedParts = [
    latencyScore(p.dataReadyMs, 1500, 3000, 5000),
    latencyScore(p.firstContentfulPaint, 1000, 1800, 3000),
    latencyScore(p.searchLatencyMs, 300, 600, 1000),
    latencyScore(p.filterLatencyMs, 300, 600, 1000),
  ].filter(v => v != null)
  const fast = speedParts.length ? speedParts.reduce((a, b) => a + b, 0) / speedParts.length : 0

  // Responsive: share of viewport checks that passed.
  const allChecks = (r.responsive || []).flatMap(v => v.checks)
  const responsive = allChecks.length
    ? (allChecks.filter(c => c.ok).length / allChecks.length) * 100
    : 0

  // Accessibility: start at 100, dock per distinct issue.
  const a11yIssues = (r.a11y?.issues || []).length
  const a11y = clamp(100 - a11yIssues * 15)

  const overall = clamp(
    usable * 0.30 +
    fast * 0.25 +
    responsive * 0.20 +
    intuitive * 0.15 +
    a11y * 0.10
  )

  return {
    dimensions: {
      Usable: Math.round(usable),
      Fast: Math.round(fast),
      Responsive: Math.round(responsive),
      Intuitive: Math.round(intuitive),
      Accessible: Math.round(a11y),
    },
    overall: Math.round(overall),
    grade: grade(overall),
    counts: {
      total: objs.length,
      passed: passed.length,
      failed: scored.length - passed.length,
      blocked: objs.length - scored.length,
    },
  }
}

const bar = (score) => {
  const filled = Math.round(score / 10)
  return '█'.repeat(filled) + '░'.repeat(10 - filled)
}

const statusIcon = { pass: '✅', fail: '❌', blocked: '⏸️' }

export function renderMarkdown(r, card) {
  const L = []
  L.push('# Usability Benchmark — James River Gooners')
  L.push('')
  L.push(`_Generated ${new Date().toISOString()} · auto-regenerated by \`npm run test:usability\`_`)
  L.push('')
  L.push(`## Overall: ${card.grade} (${card.overall}/100)`)
  L.push('')
  L.push('| Dimension | Score | |')
  L.push('|---|---:|---|')
  for (const [dim, score] of Object.entries(card.dimensions)) {
    L.push(`| ${dim} | ${score} | \`${bar(score)}\` |`)
  }
  L.push('')
  L.push(`**Objectives:** ${card.counts.passed} passed · ${card.counts.failed} failed · ${card.counts.blocked} blocked (data) of ${card.counts.total} total`)
  L.push('')

  // Per-objective table
  L.push('## Bidder objectives')
  L.push('')
  L.push('| | Persona | Goal | Steps (opt) | Time | Notes |')
  L.push('|---|---|---|---|---|---|')
  for (const o of r.objectives) {
    const steps = o.status === 'blocked' ? '—' : `${o.steps} (${o.optimalSteps})`
    const time = o.durationMs != null ? `${(o.durationMs / 1000).toFixed(1)}s` : '—'
    const notes = (o.friction || []).join('; ') || '—'
    L.push(`| ${statusIcon[o.status] || '?'} | ${o.persona} | ${o.goal} | ${steps} | ${time} | ${notes} |`)
  }
  L.push('')

  // Performance
  const p = r.perf || {}
  L.push('## Performance')
  L.push('')
  L.push('| Metric | Value | Budget |')
  L.push('|---|---:|---|')
  L.push(`| Data ready (load → grid) | ${p.dataReadyMs ?? '—'} ms | < 1500 ms |`)
  L.push(`| First contentful paint | ${p.firstContentfulPaint ?? '—'} ms | < 1000 ms |`)
  L.push(`| DOMContentLoaded | ${p.domContentLoaded ?? '—'} ms | — |`)
  L.push(`| Load complete | ${p.loadComplete ?? '—'} ms | — |`)
  L.push(`| Search latency | ${p.searchLatencyMs ?? '—'} ms | < 300 ms |`)
  L.push(`| Filter latency | ${p.filterLatencyMs ?? '—'} ms | < 300 ms |`)
  if (p.transferKB != null) L.push(`| Initial transfer | ${p.transferKB} KB | — |`)
  L.push('')

  // Responsive
  L.push('## Responsive layout')
  L.push('')
  L.push('| Viewport | Checks passed | Failures |')
  L.push('|---|---|---|')
  for (const v of (r.responsive || [])) {
    const fails = v.checks.filter(c => !c.ok).map(c => `${c.name} (${c.detail})`).join('; ') || 'none'
    const passN = v.checks.filter(c => c.ok).length
    L.push(`| ${v.viewport} | ${passN}/${v.checks.length} | ${fails} |`)
  }
  L.push('')

  // Accessibility
  L.push('## Accessibility')
  L.push('')
  const a = r.a11y || {}
  L.push(`- Interactive elements audited: **${a.interactiveCount ?? '—'}**`)
  L.push(`- Images: **${a.imageCount ?? '—'}**, Headings (h1–h3): **${a.headingCount ?? '—'}**`)
  L.push(`- Item-title contrast: **${a.bodyContrast != null ? a.bodyContrast + ':1' : '—'}** (WCAG AA needs 4.5:1)`)
  if ((a.issues || []).length) {
    L.push('- Issues:')
    for (const i of a.issues) L.push(`  - ⚠️ ${i}`)
  } else {
    L.push('- ✅ No issues flagged by the automated checks')
  }
  L.push('')

  // Console health
  if ((r.consoleErrors || []).length) {
    L.push('## Console errors observed')
    L.push('')
    const unique = [...new Set(r.consoleErrors)]
    for (const e of unique.slice(0, 10)) L.push(`- \`${e.slice(0, 160)}\``)
    L.push('')
  }

  L.push('---')
  L.push('_See `docs/UX-REVIEW.md` for the narrative findings and prioritized recommendations._')
  L.push('')
  return L.join('\n')
}

export function writeReport(r, mdPath, jsonPath) {
  const card = buildScorecard(r)
  const md = renderMarkdown(r, card)
  for (const path of [mdPath, jsonPath]) mkdirSync(dirname(path), { recursive: true })
  writeFileSync(mdPath, md)
  writeFileSync(jsonPath, JSON.stringify({ scorecard: card, results: r }, null, 2))
  return card
}
