-- Canonical category mapping (generated from scraper/category_canonical.yml
-- by scraper/build_category_table.py — DO NOT EDIT BY HAND; edit the YAML and
-- regenerate). Browsers read it via the publishable key; only the scraper /
-- service role writes.

create table if not exists public.category_mappings (
  source         text not null,           -- 'common' | 'cannons' | 'hibid' | 'rasmus'
  raw_category   text not null,           -- lowercased site category / breadcrumb leaf
  subcategory    text not null,           -- canonical mid-level name ('__unknown__' allowed)
  category_group text not null,           -- top-level display group
  primary key (source, raw_category)
);

create table if not exists public.category_groups (
  category_group text primary key,
  sort_order     int  not null
);

create table if not exists public.category_inference (
  keyword     text primary key,           -- lowercased title/description keyword
  subcategory text not null,
  priority    int  not null               -- lower = checked first
);

alter table public.category_mappings   enable row level security;
alter table public.category_groups      enable row level security;
alter table public.category_inference   enable row level security;

do $$ begin
  create policy "category_mappings_read"  on public.category_mappings  for select using (true);
  create policy "category_groups_read"    on public.category_groups     for select using (true);
  create policy "category_inference_read" on public.category_inference  for select using (true);
exception when duplicate_object then null; end $$;

-- Public read view (mirrors the public_auction_comps pattern).
create or replace view public.public_category_mappings as
  select source, raw_category, subcategory, category_group
  from public.category_mappings;

-- Idempotent reseed.
truncate public.category_mappings;
truncate public.category_groups;
truncate public.category_inference;

insert into public.category_groups (category_group, sort_order) values
  ('Art', 0),
  ('China & Glass', 1),
  ('Silver & Metal', 2),
  ('Furniture', 3),
  ('Jewelry & Watches', 4),
  ('Coins & Currency', 5),
  ('Firearms', 6),
  ('Books & Media', 7),
  ('Electronics', 8),
  ('Home & Kitchen', 9),
  ('Fashion', 10),
  ('Health & Beauty', 11),
  ('Toys & Games', 12),
  ('Rugs & Textiles', 13),
  ('Lawn & Garden', 14),
  ('Sporting Goods', 15),
  ('Hobbies', 16),
  ('Tools & Hardware', 17),
  ('Industrial & Equipment', 18),
  ('Collectibles', 19),
  ('Seasonal', 20),
  ('Vehicles', 21),
  ('Science & Nature', 22),
  ('Pets & Kids', 23),
  ('Other', 24);

insert into public.category_mappings (source, raw_category, subcategory, category_group) values
  ('common', 'accessories', 'Fashion Accessories', 'Fashion'),
  ('common', 'action figure', 'Toys & Games', 'Toys & Games'),
  ('common', 'action figures', 'Toys & Games', 'Toys & Games'),
  ('common', 'advertising', 'Collectibles', 'Collectibles'),
  ('common', 'african & ethnographic art', 'African & Ethnographic Art', 'Art'),
  ('common', 'african art', 'African & Ethnographic Art', 'Art'),
  ('common', 'air guns', 'Firearms', 'Firearms'),
  ('common', 'air rifle', 'Firearms', 'Firearms'),
  ('common', 'airgun', 'Firearms', 'Firearms'),
  ('common', 'ammo', 'Ammunition', 'Firearms'),
  ('common', 'ammunition', 'Ammunition', 'Firearms'),
  ('common', 'angle grinders', 'Power Tools', 'Tools & Hardware'),
  ('common', 'antiques', 'Collectibles', 'Collectibles'),
  ('common', 'appliances', 'Appliances', 'Home & Kitchen'),
  ('common', 'artifacts', 'Artifacts', 'Collectibles'),
  ('common', 'arts & craft', 'Hobbies & Crafts', 'Hobbies'),
  ('common', 'arts and crafts', 'Hobbies & Crafts', 'Hobbies'),
  ('common', 'audio visual', 'Audiovisual', 'Electronics'),
  ('common', 'audiovisual', 'Audiovisual', 'Electronics'),
  ('common', 'auto accessories', 'Auto Parts & Accessories', 'Vehicles'),
  ('common', 'auto parts', 'Auto Parts & Accessories', 'Vehicles'),
  ('common', 'auto parts & accessories', 'Auto Parts & Accessories', 'Vehicles'),
  ('common', 'automobile', 'Vehicles', 'Vehicles'),
  ('common', 'automobilia', 'Auto Parts & Accessories', 'Vehicles'),
  ('common', 'automotive', 'Auto Parts & Accessories', 'Vehicles'),
  ('common', 'automotive accessories', 'Auto Parts & Accessories', 'Vehicles'),
  ('common', 'aviation', 'Aviation', 'Hobbies'),
  ('common', 'avon', 'Health & Beauty', 'Health & Beauty'),
  ('common', 'baby items', 'Child Care', 'Pets & Kids'),
  ('common', 'barware', 'Kitchenware', 'Home & Kitchen'),
  ('common', 'baseball cards', 'Trading Cards', 'Collectibles'),
  ('common', 'baskets', 'Household', 'Home & Kitchen'),
  ('common', 'bathroom', 'Household', 'Home & Kitchen'),
  ('common', 'batteries', 'Hardware', 'Tools & Hardware'),
  ('common', 'batteries & power', 'Batteries & Power', 'Industrial & Equipment'),
  ('common', 'beer steins', 'Steins', 'Collectibles'),
  ('common', 'bicycles', 'Sporting Goods', 'Sporting Goods'),
  ('common', 'binoculars', 'Photography', 'Electronics'),
  ('common', 'black americana', 'Black Americana', 'Collectibles'),
  ('common', 'blankets and throws', 'Linens & Textiles', 'Rugs & Textiles'),
  ('common', 'board game', 'Board Games', 'Toys & Games'),
  ('common', 'board games', 'Board Games', 'Toys & Games'),
  ('common', 'boat & marine', 'Boat & Marine', 'Vehicles'),
  ('common', 'boat parts', 'Boat & Marine', 'Vehicles'),
  ('common', 'bookcases', 'Furniture', 'Furniture'),
  ('common', 'bookends', 'Household', 'Home & Kitchen'),
  ('common', 'books', 'Books', 'Books & Media'),
  ('common', 'boots', 'Shoes & Boots', 'Fashion'),
  ('common', 'bottles', 'Collectibles', 'Collectibles'),
  ('common', 'brassware', 'Brassware & Copper', 'Silver & Metal'),
  ('common', 'brassware & copper', 'Brassware & Copper', 'Silver & Metal'),
  ('common', 'building materials', 'Building Materials', 'Industrial & Equipment'),
  ('common', 'bullets', 'Ammunition', 'Firearms'),
  ('common', 'candles and accessories', 'Lighting', 'Home & Kitchen'),
  ('common', 'cards', 'Trading Cards', 'Collectibles'),
  ('common', 'cash register', 'Office Supplies', 'Home & Kitchen'),
  ('common', 'cast iron', 'Cast Iron', 'Silver & Metal'),
  ('common', 'cd and dvds', 'Vinyl & CDs', 'Books & Media'),
  ('common', 'cds and dvds', 'Vinyl & CDs', 'Books & Media'),
  ('common', 'ceramics', 'China & Pottery', 'China & Glass'),
  ('common', 'child care', 'Child Care', 'Pets & Kids'),
  ('common', 'china & pottery', 'China & Pottery', 'China & Glass'),
  ('common', 'china / lenox dinnerware', 'China & Pottery', 'China & Glass'),
  ('common', 'china and ceramics', 'China & Pottery', 'China & Glass'),
  ('common', 'china and dinnerware', 'China & Pottery', 'China & Glass'),
  ('common', 'china and pottery', 'China & Pottery', 'China & Glass'),
  ('common', 'christmas', 'Christmas & Holiday', 'Seasonal'),
  ('common', 'christmas & holiday', 'Christmas & Holiday', 'Seasonal'),
  ('common', 'christmas/holiday', 'Christmas & Holiday', 'Seasonal'),
  ('common', 'clocks', 'Clocks', 'Home & Kitchen'),
  ('common', 'closet contents', 'Household', 'Home & Kitchen'),
  ('common', 'clothes', 'Clothing', 'Fashion'),
  ('common', 'clothing', 'Clothing', 'Fashion'),
  ('common', 'coats / jackets', 'Clothing', 'Fashion'),
  ('common', 'coca cola', 'Collectibles', 'Collectibles'),
  ('common', 'coins', 'Coins & Currency', 'Coins & Currency'),
  ('common', 'coins & currency', 'Coins & Currency', 'Coins & Currency'),
  ('common', 'coins and currency', 'Coins & Currency', 'Coins & Currency'),
  ('common', 'collectibles', 'Collectibles', 'Collectibles'),
  ('common', 'comic books', 'Comics', 'Books & Media'),
  ('common', 'comicbooks', 'Comics', 'Books & Media'),
  ('common', 'comics', 'Comics', 'Books & Media'),
  ('common', 'computers & elec', 'Electronics', 'Electronics'),
  ('common', 'computers and printers', 'Electronics', 'Electronics'),
  ('common', 'cookbooks', 'Books', 'Books & Media'),
  ('common', 'cookware', 'Kitchenware', 'Home & Kitchen'),
  ('common', 'coolers', 'Lawn & Garden', 'Lawn & Garden'),
  ('common', 'copper', 'Brassware & Copper', 'Silver & Metal'),
  ('common', 'costume jewelry', 'Jewelry', 'Jewelry & Watches'),
  ('common', 'crafting', 'Hobbies & Crafts', 'Hobbies'),
  ('common', 'crystal', 'Crystal', 'China & Glass'),
  ('common', 'crystal and glass', 'Crystal', 'China & Glass'),
  ('common', 'cutlery', 'Knives & Swords', 'Collectibles'),
  ('common', 'decoration accessories', 'Decorative Accessories', 'Art'),
  ('common', 'decorations accessories', 'Decorative Accessories', 'Art'),
  ('common', 'decorative', 'Decorative Accessories', 'Art'),
  ('common', 'decorative accessories', 'Decorative Accessories', 'Art'),
  ('common', 'decors accessories', 'Decorative Accessories', 'Art'),
  ('common', 'disney', 'Disney', 'Toys & Games'),
  ('common', 'dolls', 'Dolls', 'Toys & Games'),
  ('common', 'dolls and doll accessories', 'Dolls', 'Toys & Games'),
  ('common', 'dolls house', 'Dolls', 'Toys & Games'),
  ('common', 'dooney and bourke', 'Purses & Bags', 'Fashion'),
  ('common', 'drill press', 'Power Tools', 'Tools & Hardware'),
  ('common', 'drones', 'Drones', 'Hobbies'),
  ('common', 'dvd/vhs', 'Vinyl & CDs', 'Books & Media'),
  ('common', 'dvds', 'Vinyl & CDs', 'Books & Media'),
  ('common', 'electronics', 'Electronics', 'Electronics'),
  ('common', 'ephemera', 'Ephemera', 'Books & Media'),
  ('common', 'equestrian', 'Equestrian', 'Sporting Goods'),
  ('common', 'ethnographic', 'African & Ethnographic Art', 'Art'),
  ('common', 'exercise & fitness', 'Exercise & Fitness', 'Sporting Goods'),
  ('common', 'exercise equipment', 'Exercise & Fitness', 'Sporting Goods'),
  ('common', 'eyewear', 'Fashion Accessories', 'Fashion'),
  ('common', 'fashion', 'Clothing', 'Fashion'),
  ('common', 'fashion accessories', 'Fashion Accessories', 'Fashion'),
  ('common', 'faux plants', 'Faux Plants', 'Home & Kitchen'),
  ('common', 'figurines', 'Sculpture', 'Art'),
  ('common', 'fire king', 'China & Pottery', 'China & Glass'),
  ('common', 'firearm accessories', 'Firearm Accessories', 'Firearms'),
  ('common', 'firearms', 'Firearms', 'Firearms'),
  ('common', 'firearms ammo & accessories', 'Firearm Accessories', 'Firearms'),
  ('common', 'fireplace', 'Fireplace', 'Home & Kitchen'),
  ('common', 'fireplace accessories', 'Fireplace', 'Home & Kitchen'),
  ('common', 'fishing', 'Fishing', 'Sporting Goods'),
  ('common', 'fishing/boating', 'Fishing', 'Sporting Goods'),
  ('common', 'fitness', 'Exercise & Fitness', 'Sporting Goods'),
  ('common', 'flatware', 'Kitchenware', 'Home & Kitchen'),
  ('common', 'food service equipment', 'Food Service Equipment', 'Industrial & Equipment'),
  ('common', 'football cards', 'Trading Cards', 'Collectibles'),
  ('common', 'footwear', 'Shoes & Boots', 'Fashion'),
  ('common', 'furniture', 'Furniture', 'Furniture'),
  ('common', 'furs', 'Clothing', 'Fashion'),
  ('common', 'games & toys', 'Toys & Games', 'Toys & Games'),
  ('common', 'gaming', 'Toys & Games', 'Toys & Games'),
  ('common', 'gemstones', 'Gemstones', 'Jewelry & Watches'),
  ('common', 'general', 'Household', 'Home & Kitchen'),
  ('common', 'glass', 'Glassware', 'China & Glass'),
  ('common', 'glasses', 'Glassware', 'China & Glass'),
  ('common', 'glassware', 'Glassware', 'China & Glass'),
  ('common', 'globes', 'Globes', 'Collectibles'),
  ('common', 'gloves', 'Clothing', 'Fashion'),
  ('common', 'gold ring', 'Jewelry', 'Jewelry & Watches'),
  ('common', 'grills', 'Lawn & Garden', 'Lawn & Garden'),
  ('common', 'hardware', 'Hardware', 'Tools & Hardware'),
  ('common', 'health & beauty', 'Health & Beauty', 'Health & Beauty'),
  ('common', 'health and beauty', 'Health & Beauty', 'Health & Beauty'),
  ('common', 'health-beauty', 'Health & Beauty', 'Health & Beauty'),
  ('common', 'heaters', 'Household', 'Home & Kitchen'),
  ('common', 'hobbies & crafts', 'Hobbies & Crafts', 'Hobbies'),
  ('common', 'hobbies and crafts', 'Hobbies & Crafts', 'Hobbies'),
  ('common', 'holiday', 'Christmas & Holiday', 'Seasonal'),
  ('common', 'holiday and seasonal', 'Christmas & Holiday', 'Seasonal'),
  ('common', 'home appliances', 'Appliances', 'Home & Kitchen'),
  ('common', 'homegoods', 'Household', 'Home & Kitchen'),
  ('common', 'hot wheels', 'Hot Wheels & Models', 'Collectibles'),
  ('common', 'hot wheels & models', 'Hot Wheels & Models', 'Collectibles'),
  ('common', 'household', 'Household', 'Home & Kitchen'),
  ('common', 'household items', 'Household', 'Home & Kitchen'),
  ('common', 'housekeeping', 'Household', 'Home & Kitchen'),
  ('common', 'housewares', 'Household', 'Home & Kitchen'),
  ('common', 'hvac & plumbing', 'HVAC & Plumbing', 'Industrial & Equipment'),
  ('common', 'industrial equipment', 'Industrial Equipment', 'Industrial & Equipment'),
  ('common', 'janitorial & cleaning', 'Janitorial & Cleaning', 'Industrial & Equipment'),
  ('common', 'jewelry', 'Jewelry', 'Jewelry & Watches'),
  ('common', 'jigs', 'Tools', 'Tools & Hardware'),
  ('common', 'kitchen', 'Kitchenware', 'Home & Kitchen'),
  ('common', 'kitchen appliances', 'Appliances', 'Home & Kitchen'),
  ('common', 'kitchenware', 'Kitchenware', 'Home & Kitchen'),
  ('common', 'knives', 'Knives & Swords', 'Collectibles'),
  ('common', 'knives & swords', 'Knives & Swords', 'Collectibles'),
  ('common', 'knives and swords', 'Knives & Swords', 'Collectibles'),
  ('common', 'lalique', 'Crystal', 'China & Glass'),
  ('common', 'lamps', 'Lighting', 'Home & Kitchen'),
  ('common', 'lawn & garden', 'Lawn & Garden', 'Lawn & Garden'),
  ('common', 'lawn and garden', 'Lawn & Garden', 'Lawn & Garden'),
  ('common', 'lawn equipment', 'Lawn & Garden', 'Lawn & Garden'),
  ('common', 'lawn mower', 'Lawn & Garden', 'Lawn & Garden'),
  ('common', 'lego', 'Lego', 'Toys & Games'),
  ('common', 'lighters', 'Collectibles', 'Collectibles'),
  ('common', 'lighting', 'Lighting', 'Home & Kitchen'),
  ('common', 'linen', 'Linens & Textiles', 'Rugs & Textiles'),
  ('common', 'linens', 'Linens & Textiles', 'Rugs & Textiles'),
  ('common', 'linens & textiles', 'Linens & Textiles', 'Rugs & Textiles'),
  ('common', 'linens and textiles', 'Linens & Textiles', 'Rugs & Textiles'),
  ('common', 'lladro', 'Decorative Accessories', 'Art'),
  ('common', 'longaberger', 'Collectibles', 'Collectibles'),
  ('common', 'luggage', 'Purses & Bags', 'Fashion'),
  ('common', 'magazines', 'Magazines', 'Books & Media'),
  ('common', 'material handling & storage', 'Material Handling & Storage', 'Industrial & Equipment'),
  ('common', 'medical', 'Medical', 'Health & Beauty'),
  ('common', 'memorabilia', 'Collectibles', 'Collectibles'),
  ('common', 'men''s apparel', 'Clothing', 'Fashion'),
  ('common', 'men’s apparel', 'Clothing', 'Fashion'),
  ('common', 'militaria', 'Military & Militaria', 'Collectibles'),
  ('common', 'military & militaria', 'Military & Militaria', 'Collectibles'),
  ('common', 'military gear', 'Military & Militaria', 'Collectibles'),
  ('common', 'miniatures', 'Hobbies & Crafts', 'Hobbies'),
  ('common', 'mirrors', 'Mirrors', 'Furniture'),
  ('common', 'model kits', 'Hot Wheels & Models', 'Collectibles'),
  ('common', 'model trains', 'Hot Wheels & Models', 'Collectibles'),
  ('common', 'motorcycle accessories', 'Auto Parts & Accessories', 'Vehicles'),
  ('common', 'mowers', 'Lawn & Garden', 'Lawn & Garden'),
  ('common', 'music', 'Vinyl & CDs', 'Books & Media'),
  ('common', 'musical instruments', 'Musical Instruments', 'Hobbies'),
  ('common', 'nail guns', 'Power Tools', 'Tools & Hardware'),
  ('common', 'native american', 'African & Ethnographic Art', 'Art'),
  ('common', 'numismatic', 'Coins & Currency', 'Coins & Currency'),
  ('common', 'office', 'Office Supplies', 'Home & Kitchen'),
  ('common', 'office products and stationary', 'Office Supplies', 'Home & Kitchen'),
  ('common', 'office supplies', 'Office Supplies', 'Home & Kitchen'),
  ('common', 'outdoor', 'Outdoor & Patio', 'Lawn & Garden'),
  ('common', 'outdoor & patio', 'Outdoor & Patio', 'Lawn & Garden'),
  ('common', 'outdoor furniture', 'Furniture', 'Furniture'),
  ('common', 'outdoors', 'Outdoor & Patio', 'Lawn & Garden'),
  ('common', 'packaging & shipping', 'Packaging & Shipping', 'Industrial & Equipment'),
  ('common', 'painting and prints', 'Paintings & Prints', 'Art'),
  ('common', 'paintings', 'Paintings & Prints', 'Art'),
  ('common', 'paintings & prints', 'Paintings & Prints', 'Art'),
  ('common', 'paintings and prints', 'Paintings & Prints', 'Art'),
  ('common', 'perfumes', 'Health & Beauty', 'Health & Beauty'),
  ('common', 'personal accessories', 'Fashion Accessories', 'Fashion'),
  ('common', 'personal care', 'Personal Care', 'Health & Beauty'),
  ('common', 'pet accessories', 'Pet Accessories', 'Pets & Kids'),
  ('common', 'pet essentials', 'Pet Accessories', 'Pets & Kids'),
  ('common', 'pets', 'Pet Accessories', 'Pets & Kids'),
  ('common', 'pewter', 'Pewter', 'Silver & Metal'),
  ('common', 'philately', 'Stamps', 'Collectibles'),
  ('common', 'photography', 'Photography', 'Electronics'),
  ('common', 'pictures/artwork', 'Paintings & Prints', 'Art'),
  ('common', 'pitchers / decanters', 'Glassware', 'China & Glass'),
  ('common', 'plush', 'Toys & Games', 'Toys & Games'),
  ('common', 'pocket watches', 'Watches', 'Jewelry & Watches'),
  ('common', 'pool accessories', 'Lawn & Garden', 'Lawn & Garden'),
  ('common', 'porcelain', 'China & Pottery', 'China & Glass'),
  ('common', 'postal history', 'Stamps', 'Collectibles'),
  ('common', 'pottery', 'China & Pottery', 'China & Glass'),
  ('common', 'power tools', 'Power Tools', 'Tools & Hardware'),
  ('common', 'prints / lithographs', 'Paintings & Prints', 'Art'),
  ('common', 'purses', 'Purses & Bags', 'Fashion'),
  ('common', 'purses & bags', 'Purses & Bags', 'Fashion'),
  ('common', 'purses & handbags', 'Purses & Bags', 'Fashion'),
  ('common', 'quilts', 'Linens & Textiles', 'Rugs & Textiles'),
  ('common', 'records', 'Vinyl & CDs', 'Books & Media'),
  ('common', 'relics', 'Artifacts', 'Collectibles'),
  ('common', 'rocks & minerals', 'Rocks & Minerals', 'Science & Nature'),
  ('common', 'rocks fossils and minerals', 'Rocks & Minerals', 'Science & Nature'),
  ('common', 'rolex', 'Watches', 'Jewelry & Watches'),
  ('common', 'roseville', 'China & Pottery', 'China & Glass'),
  ('common', 'rugs', 'Rugs', 'Rugs & Textiles'),
  ('common', 'safety & ppe', 'Safety & PPE', 'Industrial & Equipment'),
  ('common', 'saws', 'Power Tools', 'Tools & Hardware'),
  ('common', 'scientific equipment', 'Scientific Equipment', 'Science & Nature'),
  ('common', 'scouting', 'Military & Militaria', 'Collectibles'),
  ('common', 'sculpture', 'Sculpture', 'Art'),
  ('common', 'sewing', 'Hobbies & Crafts', 'Hobbies'),
  ('common', 'sewing machine', 'Hobbies & Crafts', 'Hobbies'),
  ('common', 'shed contents', 'Household', 'Home & Kitchen'),
  ('common', 'shoes', 'Shoes & Boots', 'Fashion'),
  ('common', 'shoes & boots', 'Shoes & Boots', 'Fashion'),
  ('common', 'silver and silverplate', 'Sterling & Silverplate', 'Silver & Metal'),
  ('common', 'silver plate', 'Sterling & Silverplate', 'Silver & Metal'),
  ('common', 'silverplate', 'Sterling & Silverplate', 'Silver & Metal'),
  ('common', 'small appliances', 'Appliances', 'Home & Kitchen'),
  ('common', 'socks & slippers', 'Clothing', 'Fashion'),
  ('common', 'spongeware', 'China & Pottery', 'China & Glass'),
  ('common', 'sporting goods', 'Sporting Goods', 'Sporting Goods'),
  ('common', 'sports cards', 'Trading Cards', 'Collectibles'),
  ('common', 'sports collectibles', 'Sports Collectibles', 'Collectibles'),
  ('common', 'sports equipment', 'Sporting Goods', 'Sporting Goods'),
  ('common', 'stained glass', 'Stained Glass', 'Art'),
  ('common', 'stained glassware', 'Stained Glass', 'Art'),
  ('common', 'stamp', 'Stamps', 'Collectibles'),
  ('common', 'stamps', 'Stamps', 'Collectibles'),
  ('common', 'statuary', 'Sculpture', 'Art'),
  ('common', 'steiff', 'Steiff', 'Toys & Games'),
  ('common', 'steins', 'Steins', 'Collectibles'),
  ('common', 'step ladders', 'Lawn & Garden', 'Lawn & Garden'),
  ('common', 'sterling', 'Sterling & Silverplate', 'Silver & Metal'),
  ('common', 'sterling & silverplate', 'Sterling & Silverplate', 'Silver & Metal'),
  ('common', 'sterling and silverplate', 'Sterling & Silverplate', 'Silver & Metal'),
  ('common', 'sterling silver', 'Sterling & Silverplate', 'Silver & Metal'),
  ('common', 'sterling silver and silverplate', 'Sterling & Silverplate', 'Silver & Metal'),
  ('common', 'steuben', 'Crystal', 'China & Glass'),
  ('common', 'stoneware', 'China & Pottery', 'China & Glass'),
  ('common', 'storage', 'Household', 'Home & Kitchen'),
  ('common', 'storage containers', 'Household', 'Home & Kitchen'),
  ('common', 'swarovski', 'Crystal', 'China & Glass'),
  ('common', 'tableware', 'Kitchenware', 'Home & Kitchen'),
  ('common', 'taxidermy', 'Taxidermy', 'Science & Nature'),
  ('common', 'tcg collectibles', 'Trading Cards', 'Collectibles'),
  ('common', 'telephone', 'Electronics', 'Electronics'),
  ('common', 'textiles', 'Linens & Textiles', 'Rugs & Textiles'),
  ('common', 'thermometer', 'Household', 'Home & Kitchen'),
  ('common', 'timepieces', 'Watches', 'Jewelry & Watches'),
  ('common', 'tobacciana', 'Tobacciana', 'Collectibles'),
  ('common', 'tools', 'Tools', 'Tools & Hardware'),
  ('common', 'tools & hardware', 'Tools', 'Tools & Hardware'),
  ('common', 'tools and hardware', 'Tools', 'Tools & Hardware'),
  ('common', 'toys', 'Toys & Games', 'Toys & Games'),
  ('common', 'toys & games', 'Toys & Games', 'Toys & Games'),
  ('common', 'toys and games', 'Toys & Games', 'Toys & Games'),
  ('common', 'trading cards', 'Trading Cards', 'Collectibles'),
  ('common', 'travel', 'Purses & Bags', 'Fashion'),
  ('common', 'treenware', 'Decorative Accessories', 'Art'),
  ('common', 'vacuum', 'Household', 'Home & Kitchen'),
  ('common', 'vases / jars', 'Glassware', 'China & Glass'),
  ('common', 'vehicles', 'Vehicles', 'Vehicles'),
  ('common', 'video games', 'Video Games', 'Books & Media'),
  ('common', 'vintage', 'Collectibles', 'Collectibles'),
  ('common', 'vintage board games', 'Board Games', 'Toys & Games'),
  ('common', 'vintage clothing', 'Clothing', 'Fashion'),
  ('common', 'vinyl & cds', 'Vinyl & CDs', 'Books & Media'),
  ('common', 'vinyl lp records', 'Vinyl & CDs', 'Books & Media'),
  ('common', 'watches', 'Watches', 'Jewelry & Watches'),
  ('common', 'waterford', 'Crystal', 'China & Glass'),
  ('common', 'women''s apparel', 'Clothing', 'Fashion'),
  ('common', 'women’s apparel', 'Clothing', 'Fashion'),
  ('common', 'yard and garden', 'Lawn & Garden', 'Lawn & Garden'),
  ('cannons', 'air hammer', 'Tools', 'Tools & Hardware'),
  ('cannons', 'ambulatory', 'Medical', 'Health & Beauty'),
  ('cannons', 'ammo/gun accessories', 'Firearm Accessories', 'Firearms'),
  ('cannons', 'amusement rides', 'Industrial Equipment', 'Industrial & Equipment'),
  ('cannons', 'animatronic', 'Industrial Equipment', 'Industrial & Equipment'),
  ('cannons', 'art', 'Paintings & Prints', 'Art'),
  ('cannons', 'baseball', 'Sports Collectibles', 'Collectibles'),
  ('cannons', 'bat', 'Sporting Goods', 'Sporting Goods'),
  ('cannons', 'boat parts', 'Boat & Marine', 'Vehicles'),
  ('cannons', 'bounce house', 'Toys & Games', 'Toys & Games'),
  ('cannons', 'bounce houses', 'Toys & Games', 'Toys & Games'),
  ('cannons', 'building supplies', 'Building Materials', 'Industrial & Equipment'),
  ('cannons', 'clamps', 'Tools', 'Tools & Hardware'),
  ('cannons', 'compressor', 'Industrial Equipment', 'Industrial & Equipment'),
  ('cannons', 'costumes', 'Clothing', 'Fashion'),
  ('cannons', 'decoys', 'Collectibles', 'Collectibles'),
  ('cannons', 'helmet', 'Sporting Goods', 'Sporting Goods'),
  ('cannons', 'herman miller', 'Furniture', 'Furniture'),
  ('cannons', 'jacks', 'Tools', 'Tools & Hardware'),
  ('cannons', 'jersey', 'Sports Collectibles', 'Collectibles'),
  ('cannons', 'jewelry/coins', 'Coins & Currency', 'Coins & Currency'),
  ('cannons', 'ladders', 'Hardware', 'Tools & Hardware'),
  ('cannons', 'materials', 'Household', 'Home & Kitchen'),
  ('cannons', 'media', 'Vinyl & CDs', 'Books & Media'),
  ('cannons', 'pets', 'Pet Accessories', 'Pets & Kids'),
  ('cannons', 'picture', 'Paintings & Prints', 'Art'),
  ('cannons', 'plaques', 'Collectibles', 'Collectibles'),
  ('cannons', 'playground', 'Toys & Games', 'Toys & Games'),
  ('cannons', 'plumbing', 'HVAC & Plumbing', 'Industrial & Equipment'),
  ('cannons', 'pokemon', 'Trading Cards', 'Collectibles'),
  ('cannons', 'pokémon', 'Trading Cards', 'Collectibles'),
  ('cannons', 'polisher', 'Power Tools', 'Tools & Hardware'),
  ('cannons', 'political memorabilia', 'Collectibles', 'Collectibles'),
  ('cannons', 'portrait', 'Paintings & Prints', 'Art'),
  ('cannons', 'pumps', 'Industrial Equipment', 'Industrial & Equipment'),
  ('cannons', 'restaurant eqt', 'Food Service Equipment', 'Industrial & Equipment'),
  ('cannons', 'safe', 'Household', 'Home & Kitchen'),
  ('cannons', 'sports jerseys', 'Sports Collectibles', 'Collectibles'),
  ('cannons', 'trunks', 'Furniture', 'Furniture'),
  ('cannons', 'wedding dress', 'Clothing', 'Fashion'),
  ('cannons', 'yard', 'Lawn & Garden', 'Lawn & Garden'),
  ('hibid', 'auto accessories', 'Auto Parts & Accessories', 'Vehicles'),
  ('hibid', 'baseball trading cards', 'Trading Cards', 'Collectibles'),
  ('hibid', 'basketball trading cards', 'Trading Cards', 'Collectibles'),
  ('hibid', 'bed / bath items', 'Household', 'Home & Kitchen'),
  ('hibid', 'bicycles, scooters & more', 'Sporting Goods', 'Sporting Goods'),
  ('hibid', 'canada', 'Collectibles', 'Collectibles'),
  ('hibid', 'civil war', 'Military & Militaria', 'Collectibles'),
  ('hibid', 'commemorative', 'Coins & Currency', 'Coins & Currency'),
  ('hibid', 'daisy pellet gun', 'Firearms', 'Firearms'),
  ('hibid', 'dimes', 'Coins & Currency', 'Coins & Currency'),
  ('hibid', 'displays / display cases', 'Household', 'Home & Kitchen'),
  ('hibid', 'dollars', 'Coins & Currency', 'Coins & Currency'),
  ('hibid', 'football trading cards', 'Trading Cards', 'Collectibles'),
  ('hibid', 'gold', 'Coins & Currency', 'Coins & Currency'),
  ('hibid', 'gold coins (pre-1933)', 'Coins & Currency', 'Coins & Currency'),
  ('hibid', 'half dollars', 'Coins & Currency', 'Coins & Currency'),
  ('hibid', 'international', 'Collectibles', 'Collectibles'),
  ('hibid', 'kitchen / home', 'Household', 'Home & Kitchen'),
  ('hibid', 'kitchen / housewares', 'Kitchenware', 'Home & Kitchen'),
  ('hibid', 'knives / blades', 'Knives & Swords', 'Collectibles'),
  ('hibid', 'medals / badges / insignias', 'Military & Militaria', 'Collectibles'),
  ('hibid', 'mixed lot', 'Collectibles', 'Collectibles'),
  ('hibid', 'mixed lots', 'Coins & Currency', 'Coins & Currency'),
  ('hibid', 'music - cds / records / cassettes', 'Vinyl & CDs', 'Books & Media'),
  ('hibid', 'nickels', 'Coins & Currency', 'Coins & Currency'),
  ('hibid', 'outdoor games & sports equipment', 'Sporting Goods', 'Sporting Goods'),
  ('hibid', 'pennies', 'Coins & Currency', 'Coins & Currency'),
  ('hibid', 'quarters', 'Coins & Currency', 'Coins & Currency'),
  ('hibid', 'sets', 'Coins & Currency', 'Coins & Currency'),
  ('hibid', 'silver', 'Coins & Currency', 'Coins & Currency'),
  ('hibid', 'specialty / collectible / novelty', 'Collectibles', 'Collectibles'),
  ('hibid', 'us', 'Collectibles', 'Collectibles'),
  ('hibid', 'vintage / antique toys', 'Toys & Games', 'Toys & Games'),
  ('hibid', 'women''s accessories', 'Fashion Accessories', 'Fashion'),
  ('hibid', 'world', 'Coins & Currency', 'Coins & Currency'),
  ('hibid', 'world war ii', 'Military & Militaria', 'Collectibles'),
  ('rasmus', 'apparel & accessories', 'Clothing', 'Fashion'),
  ('rasmus', 'appliances', 'Appliances', 'Home & Kitchen'),
  ('rasmus', 'auto parts & eqpt', 'Auto Parts & Accessories', 'Vehicles'),
  ('rasmus', 'batteries & chargers', 'Batteries & Power', 'Industrial & Equipment'),
  ('rasmus', 'books & media', 'Books', 'Books & Media'),
  ('rasmus', 'building materials', 'Building Materials', 'Industrial & Equipment'),
  ('rasmus', 'cleaning & janitorial', 'Janitorial & Cleaning', 'Industrial & Equipment'),
  ('rasmus', 'computers & elec', 'Electronics', 'Electronics'),
  ('rasmus', 'exercise & fitness eqpt', 'Exercise & Fitness', 'Sporting Goods'),
  ('rasmus', 'food service eqpt', 'Food Service Equipment', 'Industrial & Equipment'),
  ('rasmus', 'furniture', 'Furniture', 'Furniture'),
  ('rasmus', 'furniture & tables', 'Furniture', 'Furniture'),
  ('rasmus', 'games & toys', 'Toys & Games', 'Toys & Games'),
  ('rasmus', 'garden & lawn eqpt', 'Lawn & Garden', 'Lawn & Garden'),
  ('rasmus', 'garden/outdoor', 'Outdoor & Patio', 'Lawn & Garden'),
  ('rasmus', 'hand & power tools', 'Power Tools', 'Tools & Hardware'),
  ('rasmus', 'home appliances', 'Appliances', 'Home & Kitchen'),
  ('rasmus', 'housewares', 'Household', 'Home & Kitchen'),
  ('rasmus', 'hvac & plumbing', 'HVAC & Plumbing', 'Industrial & Equipment'),
  ('rasmus', 'ind & warehouse eqpt', 'Industrial Equipment', 'Industrial & Equipment'),
  ('rasmus', 'lighting', 'Lighting', 'Home & Kitchen'),
  ('rasmus', 'medical & healthcare', 'Medical', 'Health & Beauty'),
  ('rasmus', 'office supplies & eqpt', 'Office Supplies', 'Home & Kitchen'),
  ('rasmus', 'outdoor & camping gear', 'Outdoor & Patio', 'Lawn & Garden'),
  ('rasmus', 'packaging & shipping', 'Packaging & Shipping', 'Industrial & Equipment'),
  ('rasmus', 'personal care products', 'Personal Care', 'Health & Beauty'),
  ('rasmus', 'safety eqpt & ppe', 'Safety & PPE', 'Industrial & Equipment'),
  ('rasmus', 'shelving & storage', 'Material Handling & Storage', 'Industrial & Equipment'),
  ('rasmus', 'snow removal eqpt', 'Industrial Equipment', 'Industrial & Equipment'),
  ('rasmus', 'specialty eqpt', 'Industrial Equipment', 'Industrial & Equipment'),
  ('rasmus', 'sporting goods', 'Sporting Goods', 'Sporting Goods'),
  ('rasmus', 'tools', 'Tools', 'Tools & Hardware');

insert into public.category_inference (keyword, subcategory, priority) values
  ('rifle', 'Firearms', 0),
  ('pistol', 'Firearms', 1),
  ('shotgun', 'Firearms', 2),
  ('revolver', 'Firearms', 3),
  ('firearm', 'Firearms', 4),
  ('ammunition', 'Ammunition', 5),
  ('handbag', 'Purses & Bags', 6),
  ('hand bag', 'Purses & Bags', 7),
  ('purse', 'Purses & Bags', 8),
  ('tote bag', 'Purses & Bags', 9),
  ('leather bag', 'Purses & Bags', 10),
  ('coach leather', 'Purses & Bags', 11),
  ('doctor''s bag', 'Purses & Bags', 12),
  ('necklace', 'Jewelry', 13),
  ('bracelet', 'Jewelry', 14),
  ('earring', 'Jewelry', 15),
  ('pendant', 'Jewelry', 16),
  ('brooch', 'Jewelry', 17),
  ('diamond', 'Jewelry', 18),
  ('gemstone', 'Gemstones', 19),
  ('wristwatch', 'Watches', 20),
  ('silver dollar', 'Coins & Currency', 21),
  ('gold eagle', 'Coins & Currency', 22),
  ('trading card', 'Trading Cards', 23),
  ('baseball card', 'Trading Cards', 24),
  ('football card', 'Trading Cards', 25),
  ('basketball card', 'Trading Cards', 26),
  ('sports card', 'Trading Cards', 27),
  ('rookie card', 'Trading Cards', 28),
  ('psa graded', 'Trading Cards', 29),
  ('topps', 'Trading Cards', 30),
  ('panini', 'Trading Cards', 31),
  ('comic book', 'Comics', 32),
  ('sofa', 'Furniture', 33),
  ('dresser', 'Furniture', 34),
  ('chest of drawers', 'Furniture', 35),
  ('bookcase', 'Furniture', 36),
  ('armoire', 'Furniture', 37),
  ('sideboard', 'Furniture', 38),
  ('nightstand', 'Furniture', 39),
  ('dining table', 'Furniture', 40),
  ('camera', 'Photography', 41),
  ('television', 'Audiovisual', 42),
  ('stereo', 'Audiovisual', 43),
  ('speaker', 'Audiovisual', 44),
  ('laptop', 'Electronics', 45),
  ('computer', 'Electronics', 46),
  ('oil on canvas', 'Paintings & Prints', 47),
  ('watercolor', 'Paintings & Prints', 48),
  ('lithograph', 'Paintings & Prints', 49),
  ('etching', 'Paintings & Prints', 50),
  ('sculpture', 'Sculpture', 51),
  ('bronze', 'Sculpture', 52),
  ('porcelain', 'China & Pottery', 53),
  ('stoneware', 'China & Pottery', 54),
  ('crystal', 'Crystal', 55),
  ('sterling silver', 'Sterling & Silverplate', 56),
  ('silverplate', 'Sterling & Silverplate', 57),
  ('pewter', 'Pewter', 58),
  ('oriental rug', 'Rugs', 59),
  ('persian rug', 'Rugs', 60),
  ('quilt', 'Linens & Textiles', 61),
  ('drill', 'Tools', 62),
  ('wrench', 'Tools', 63),
  ('saw', 'Tools', 64),
  ('book', 'Books', 65),
  ('fishing', 'Fishing', 66),
  ('golf', 'Sporting Goods', 67),
  ('bicycle', 'Sporting Goods', 68),
  ('doll', 'Dolls', 69),
  ('lego', 'Lego', 70),
  ('cookware', 'Kitchenware', 71),
  ('lawn mower', 'Lawn & Garden', 72),
  ('action figure', 'Toys & Games', 73),
  ('board game', 'Board Games', 74),
  ('vinyl record', 'Vinyl & CDs', 75),
  ('stamp', 'Stamps', 76),
  ('postal history', 'Stamps', 77);
